### ISSUE TITLE
Damn so skidded 💀

### ISSUE THREAD

**Issue by TheKindDeveloper** [Xvirus0/Xvirus-Tools#11]
This skid is stuck at v6 api, hes defently stuck

**Comment by Cwackz** [comment]
> This skid is stuck at v6 api, hes defently stuck

Mind going into detail why you would think this is skidded? And you might want to change your github name 😃

**Comment by TheKindDeveloper** [comment]
> > This skid is stuck at v6 api, hes defently stuck
> 
> Mind going into detail why you would think this is skidded? And you might want to change your github name 😃

Shit pasted af everyone with a brain uses the newest api cwackz 😘

**Comment by Cwackz** [comment]
> > > This skid is stuck at v6 api, hes defently stuck
> > 
> > 
> > Mind going into detail why you would think this is skidded? And you might want to change your github name 😃
> 
> Shit pasted af everyone with a brain uses the newest api cwackz 😘

Find the same source and i'll admit its skidded, if you can't thats because it isn't skidded 😸 
We've also changed to the newest api for your sake ❤️

**Comment by TheKindDeveloper** [comment]
> 

dont care this tool is still ass, bypass on top

**Comment by Cwackz** [comment]
> > 
> 
> dont care this tool is still ass, bypass on top

You mean your shitty code where you defined everything in the same file 😭

**Comment by TheKindDeveloper** [comment]
lmfao bypass is known this ass tool has 20 stars gtfo

**Comment by DXVVAY** [comment]
if its know why havnt I heard about in the 4 years ive been programming lmao

**Comment by TheKindDeveloper** [comment]
> if its know why havnt I heard about in the 4 years ive been programming lmao

it is known lmfao even your friend benjamin knows about it 🤣🤣

**Comment by DXVVAY** [comment]
Yk what idgaf just go and work on it without bothering other people and just fucken grow up

**Comment by TheKindDeveloper** [comment]
> Yk what idgaf just go and work on it without bothering other people and just fucken grow up

yea just go work on your shitty ass tkn gen 😘, skid

**Comment by Cwackz** [comment]
> > if its know why havnt I heard about in the 4 years ive been programming lmao
> 
> it is known lmfao even your friend benjamin knows about it 🤣🤣

I only found it cause you have a github repo for the website 😭

**Comment by TheKindDeveloper** [comment]
> > > if its know why havnt I heard about in the 4 years ive been programming lmao
> > 
> > 
> > it is known lmfao even your friend benjamin knows about it 🤣🤣
> 
> I only found it cause you have a github repo for the website 😭

lmao it had 15k on youtube
