### ISSUE TITLE
Error when running  setup

### ISSUE THREAD

**Issue by Huntercrocker11** [Xvirus0/Xvirus-Tools#15]
pip install http.client

Collecting http.client
  Using cached http_client-0.1.22.tar.gz (1.6 kB)
  Preparing metadata (setup.py) ... done
Collecting pycurl (from http.client)
  Using cached pycurl-7.45.2.tar.gz (234 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 10
  ╰─> [1 lines of output]
      Please specify --curl-dir=/path/to/built/libcurl
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by DXVVAY** [comment]
Does it still work tho?

**Comment by Huntercrocker11** [comment]
> 
no i get,

Traceback (most recent call last):
  File "\Xvirus-Tools-main\util\plugins\common.py", line 526, in <module>
    username = get_username()
  File "\Xvirus-Tools-main\util\plugins\common.py", line 518, in get_username
    usernamelogo()
NameError: name 'usernamelogo' is not defined

**Comment by DXVVAY** [comment]
Have you updated?

**Comment by DXVVAY** [comment]
Jut redownload the tool
