### ISSUE TITLE
add a logger

### ISSUE THREAD

**Issue by cocorico8** [Xvirus0/Xvirus-Tools#21]
like that when something get write and the program close instanlty after we can debug more easily

**Comment by DXVVAY** [comment]
I think i might have a solution for that ill see what i can do

**Comment by DXVVAY** [comment]
Should A error logs.txt be good? So it saves them into a txt file

**Comment by cocorico8** [comment]
yhea absolutely

**Comment by GameMaster56001** [comment]
alot of functions not working like token info, qr code grabber, rat bot, and i keep get rate limited in mass report but yeah everything other than that is good

**Comment by GameMaster56001** [comment]
and also for mass report it says: Error: {"message": "Invalid API version", "code": 50041} | Status Code: 400 and it also says global: false
