### ISSUE TITLE
functions

### ISSUE THREAD

**Issue by GameMaster56001** [Xvirus0/Xvirus-Tools#22]
alot of functions not working like token info, qr code grabber, rat bot, and i keep get rate limited in mass report but yeah everything other than that is good
and also for mass report it says: Error: {"message": "Invalid API version", "code": 50041} | Status Code: 400 and it also says global: false
oh and the group spammer isnt working properly too

**Comment by DXVVAY** [comment]
thanks ill look into it

**Comment by DXVVAY** [comment]
Rat bot and token info works now im trying to fix the rest now

**Comment by DXVVAY** [comment]
fixed groupchat spammer
