### ISSUE TITLE
sh: 1: cls: not found

### ISSUE THREAD

**Issue by BoBoB63** [Xvirus0/Xvirus-Tools#24]
sh: 1: cls: not found

**Comment by DXVVAY** [comment]
Can you provide more information?

**Comment by BoBoB63** [comment]
> Can you provide more information?
sh: 1: cls: not found
Traceback (most recent call last):
  File "/home/kali/Xvirus-Tools/Xvirus.py", line 535, in <module>
    setTitle("Xvirus Loading...")
  File "/home/kali/Xvirus-Tools/util/plugins/common.py", line 169, in setTitle
    os.system(f"\033]0;{_str} | Made By Xvirus\a", end='', flush=True)
TypeError: system() takes at most 1 argument (3 given)

**Comment by LopeKinz** [comment]
cls is a command for windows use clear for linux
